### PR TITLE
[IGNORE] Enable CI for Gemstone and correct missing compatibility

### PR DESCRIPTION
**Pull request by jecisc**
Still not working for now:

`  Executed 569 Tests with 4 Failures and 3 Errors in 0.10s.`

### CODE REVIEW

**Comment by jecisc** [comment]
@pdebruic The only failures that are still here are linked to OrderedDictionary and its subclass. 

Can you take a look please?

**Comment by jecisc** [comment]
Also would you wind if I move this project to DuneSt? I do not like the fact that it loads one package from a different repo without versionning. 

I would like to make it a versionned project on which peolpe can do PR. Same for the PackageManifest.

**Comment by pdebruic** [comment]
Can you provide a link to the failures?  Are they not explained by the commit message for the OrderedDictionary package?

**Comment by pdebruic** [comment]
I don't think this package is at all seaside specific.  Why do you want to clutter your new seaside additions group with this?  Also limits discoverability from GS perspective. Might be better in e.g. github.com/gsdevkit



Maybe instead you can add the classes MDL & MDLColor require to the Baseline of the pharo compatability package you found, and load it from there.  



But I think moving it anywhere is fine.  MIT and all.

**Comment by jecisc** [comment]
@pdebruic I just read the message and yes this explains the failures. I'll try to change the tests to not fail the build and also as I said if it's fine with you I move the OrderedDictionary to this project:

https://github.com/DuneSt/OrderedDictionary

Like that, I'll be able to keep semantic versioning without problem.

**Comment by pdebruic** [comment]
Also are you able to develop on GemStone yet?  If not it seems strange to move GS specific packages around until you can and have time to maintain it. But again, I don't have a problem with you doing whatever you want with the GS specific OrderedDictionary classes or PackageManifest stub.

**Comment by jecisc** [comment]
The problem is that I'm not part of gsdevkit. 

I'll ask Dale if he can add me and in that case, yes I'll add the projects to this organisation.

**Comment by jecisc** [comment]
I could install Gemstone on a VirtualMachine. It's still pretty new to me but at least with that and the CI I'm able to do some things :)

I could not install MDL and launch the demo... But at least I can browse the code and check the tests.

**Comment by jecisc** [comment]
@pdebruic I sent a mail to Dale asking to be added to the organisation.

**Comment by pdebruic** [comment]
Sounds great to me.  Glad you were able to get GemStone running.

**Comment by jecisc** [comment]
I got the rights on GsDevKit organization. I'll finish this release just after ESUG :)

**Pull request merged**
